version: '3.9'
services:
  user-elasticsearch:
    container_name: user-elasticsearch
    image: elasticsearch:8.7.1
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
      xpack.security.enabled: false
